config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  ### Landing Page
  root 'welcome#index'
  get 'welcome/index'
  ########################################################################

  ### User Routes
  devise_for :users, controllers: { confirmations: 'confirmations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ########################################################################
  
  ### Prdoduct Routes
  get "/fetch_products" => 'products#filter_products', as: 'fetch_products'
  resources :products
  ########################################################################

  ### Cart Routes
  get 'carts', to: 'carts#index', as: 'carts'
  post 'add.to.cart/:id', to: 'carts#create', as: 'add_to_cart'
  put 'cart/:id', to: 'carts#update', as: 'cart'
  delete 'remove.product/:id', to: 'carts#remove', as: 'remove_product'
  delete 'remove.cart/:id', to: 'carts#destroy', as: 'remove_cart'
  ########################################################################

  ### Order Routes
  get 'orders', to: 'orders#index', as: 'orders'
  get 'order/:id/edit', to: 'orders#edit', as: 'edit_order'
  put 'order/:id', to: 'orders#update', as: 'order'
  ########################################################################

  ### Store_Orders Routes
  get 'store.orders', to: 'store_orders#index', as: 'store_orders'
  get 'store.history', to: 'store_orders#history', as: 'store_history'
  put 'store.response/:id', to: 'store_orders#update', as: 'store_response'
  ########################################################################
  
  ### Reviews Routes
  post "rate.product/:id" => 'reviews#rate', as: 'rate_product'
  post "comment.product/:id" => 'reviews#comment', as: 'comment_product'
  ########################################################################
  
  ### Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  ########################################################################

  #Product API Routes
  namespace :api do
    resources :products
  end

end

app/controllers/store_orders_controller.rb
class StoreOrdersController < ApplicationController
  before_action :authenticate_user!
  
    def index
      if !(current_user.store).nil?
        @store_orders = OrderProduct.where(store_id: current_user.store.id)
        @orders = @store_orders.where(state: "pending").or(@store_orders.where(state: "confirmed")).page params[:page]
      else
        redirect_to orders_path, alert: 'you do not have store!'
      end
    end
  
    def history
      if !(current_user.store).nil?
        @store_orders = OrderProduct.where(store_id: current_user.store.id)
        @orders = @store_orders.where(state: "delivered").order(created_at: :desc).page params[:page]
      else
        redirect_to orders_path, alert: 'you do not have store!'
      end
    end

    def update
        @order = OrderProduct.find(params[:id])
        if @order.state == "pending" || @order.state == "confirmed"
          if @order.order.state == "pending"
            update_orders("confirmed")
            redirect_to request.referrer
          end
          if @order.order.state == "confirmed"
            update_orders("delivered")
            redirect_to request.referrer
          end
        end
    end

    private

    def store_orders_params
        params.permit(:id, :state, :page)
    end

    def update_orders(stat)
      @order.update(state: stat)
      @orders = OrderProduct.where(order_id: @order.order_id)
      if @orders.where(state: @order.order.state).empty?
        Order.find(@order.order_id).update(state: stat)
        if stat == "delivered"
          Address.find_by(order_id: @order.order_id).destroy
        end
      end
    end
  
end

app/helpers/store_orders_helper.rb
module StoreOrdersHelper
end

app/views/store_orders/history.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 border p-1 m-5">
      <h1 class="text-center mt-3 m-2 bg-success rounded shadow"><%= current_user.store.name%> Store History</h1>
      <hr />
      <div class="m-3">
        <% if ! @orders.empty? %>
          <table class="table table-sm table-striped shadow rounded text-center">
            <thead class="thead-dark">
              <tr>
                <th>Product</th>
                <th>Data</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr class="">
                  <td><%= link_to product_path(order.product.id), :class => 'text-decoration-none text-dark' do %>
                      <%= order.product.title %>
                    <% end %></td>
                  <td><%= order.created_at %></td>
                  <td><%= order.quantity %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <table class="table table table-striped shadow rounded text-center mb-4">
            <tr>
              <td colspan="6" class="text-center h4">No Orders</td>
            </tr>
          </table>
        <% end %>
        <% if @orders.present? %>
        <div class="apple_pagination border shadow rounded mt-5 p-1">
            <%= paginate @orders %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/store_orders/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 border p-1 m-5">
      <h1 class="text-center mt-3 m-2 bg-success rounded shadow"><%= current_user.store.name%> Store Orders</h1>
      <hr />
      <div class="m-3">
        <% if ! @orders.empty? %>
          <% @orders.each do |order| %>
            <table class="table table-sm table-striped shadow rounded text-center">
              <thead class="thead-dark">
                <tr>
                  <th>Product</th>
                  <th>Image</th>
                  <th>Total Price</th>
                  <th>Quantity</th>
                  <th>Available Quantity</th>
                </tr>
              </thead>
              <tbody>
                <tr class="">
                  <td><%= link_to product_path(order.product.id), :class => 'text-decoration-none text-dark' do %>
                      <%= order.product.title %>
                    <% end %></td>
                  <td><%= (order.product.image.attached?) ? image_tag(order.product.image, size: "120x100") : "No Image" %></td>
                  <td><%= order.quantity*order.product.price %></td>
                  <td><%= order.quantity %></td>
                  <td><%= order.product.quantity %></td>
                </tr>
                <tr>
                  <th colspan="2" class="bg-dark text-center text-white h6">Order Address</th>
                  <th colspan="2" class="bg-dark text-center text-white h6">State</th>
                  <th colspan="1" class="bg-dark text-center text-white h6">Action</th>
                </tr>
                <tr class="table-info text-dark">
                  <td colspan="2"><%= order.order.address.address %></td>
                  <td colspan="2" class="text-center h5"><%= order.state %></td>
                  <td colspan="1" class="text-center h5">
                    <% if order.state == 'pending' %>
                      <%= link_to "confirm", store_response_path(order.id), class: 'btn btn-success shadow', method: :put %>
                    <% else %>
                      <% if order.order.state == 'confirmed' %>
                        <%= link_to "deliver", store_response_path(order.id), class: 'btn btn-warning shadow', method: :put %>
                      <% else %>
                        <p>Waiting..</p>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              </tbody>
            </table>
          <% end %>
        <% else %>
          <table class="table table table-striped shadow rounded text-center mb-4">
            <tr>
              <td colspan="6" class="text-center h4">No Orders</td>
            </tr>
          </table>
        <% end %>
        <% if @orders.present? %>
        <div class="apple_pagination border shadow rounded mt-5 p-1">
            <%= paginate @orders %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>