config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  ### Landing Page
  root 'welcome#index'
  get 'welcome/index'
  ########################################################################

  ### User Routes
  devise_for :users, controllers: { confirmations: 'confirmations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ########################################################################
  
  ### Prdoduct Routes
  get "/fetch_products" => 'products#filter_products', as: 'fetch_products'
  resources :products
  ########################################################################

  ### Cart Routes
  get 'carts', to: 'carts#index', as: 'carts'
  post 'add.to.cart/:id', to: 'carts#create', as: 'add_to_cart'
  put 'cart/:id', to: 'carts#update', as: 'cart'
  delete 'remove.product/:id', to: 'carts#remove', as: 'remove_product'
  delete 'remove.cart/:id', to: 'carts#destroy', as: 'remove_cart'
  ########################################################################

  ### Order Routes
  get 'orders', to: 'orders#index', as: 'orders'
  get 'order/:id/edit', to: 'orders#edit', as: 'edit_order'
  put 'order/:id', to: 'orders#update', as: 'order'
  ########################################################################

  ### Store_Orders Routes
  get 'store.orders', to: 'store_orders#index', as: 'store_orders'
  get 'store.history', to: 'store_orders#history', as: 'store_history'
  put 'store.response/:id', to: 'store_orders#update', as: 'store_response'
  ########################################################################
  
  ### Reviews Routes
  post "rate.product/:id" => 'reviews#rate', as: 'rate_product'
  post "comment.product/:id" => 'reviews#comment', as: 'comment_product'
  ########################################################################
  
  ### Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  ########################################################################

  #Product API Routes
  namespace :api do
    resources :products
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cart = Order.find_by(user_id: current_user.id, state: "inCart")
  end

  def create
    if Product.find(params[:id]).quantity == 0
      redirect_to products_path, alert: Product.find(params[:id]) + 'Cannot add it, no available items for your order'
    else
      @order = Order.find_by(user_id: current_user.id, state: "inCart")

      if @order.nil?
        @order =Order.create(user_id: current_user.id, state: "inCart")
      end
      update(@order, params[:id], params[:quantity])

      redirect_to request.referrer, notice: Product.find(params[:id]).title + ' added to cart successfully'
    end
  end

  def edit
  end

  def update(order, prod_id, quantity)
        if quantity.nil?
          orderprod(order.id, prod_id)
        else
          orderprod(order.id, prod_id, quantity.to_i)
        end
  end

  def destroy
    @order = Order.find(params[:id])
    @orderprod = OrderProduct.find_by(order_id: @order.id)
    @orderprod.destroy
    @order.destroy
    redirect_to request.referrer, notice: 'Deleted successfully'
  end

  def remove
      @orderprod = OrderProduct.find(params[:id])
      orderid = @orderprod.order_id
      @orderprod.destroy
      if OrderProduct.where(order_id: orderid).empty?
        Order.find_by(id: orderid, state: "inCart").destroy
      end
      redirect_to request.referrer, notice: 'Removed successfully'
  end

  private

  def cart_params
      params.permit(:id, :quantity)
  end

  def orderprod (ord_id, prd_id, quantity = 1)
    @orderprod = OrderProduct.find_by(order_id: ord_id, product_id: prd_id)
    
    if @orderprod.nil?
      @product = Product.find(prd_id)
      Order.find(ord_id).products << @product
      @orderprod = OrderProduct.find_by(order_id: ord_id, product_id: prd_id)
      @orderprod.update(store_id: @product.store.id, state: "inCart", quantity: quantity)
    elsif @orderprod.quantity > 0
      unless @orderprod.quantity == 1 && quantity == -1
        @orderprod.update(quantity: @orderprod.quantity+quantity)
      end
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10 border p-1 m-5">
      <h1 class="text-center mt-3 m-2 bg-warning rounded shadow">My Cart</h1>
      <hr />
      <div class="m-3">
        <% if ! @cart.nil? %>
          <table class="table table-sm table-striped shadow rounded text-center">
            <thead class="thead-dark">
              <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Image</th>
                <th>Total Price</th>
                <th colspan="3">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @cart.order_products.each do |ordprod| %>
                <tr>
                  <td><%= link_to product_path(ordprod.product.id), :class => 'text-decoration-none text-dark' do %>
                      <%= ordprod.product.title %>
                    <% end %></td>
                  <td><%= ordprod.quantity %></td>
                  <td><%= (ordprod.product.image.attached?) ? image_tag(ordprod.product.image, size: "120x100") : "No Image" %></td>
                  <td><%= ordprod.quantity * ordprod.product.price %></td>
                  <td><%= link_to 'x', remove_product_path(ordprod.id), method: :delete, class: 'btn btn-danger font-weight-bold' , data: { confirm: 'Are you sure?' } %></p>
                </td>
                <td><%= link_to '+', add_to_cart_path(ordprod.product.id), class: 'btn btn-success font-weight-bold', method: :post %></p>
              </td>
              <td>
                <%= form_with(url: add_to_cart_path(ordprod.product.id), method: "post") do |form| %>
                  <%= form.hidden_field  :quantity ,value: -1, min: -1, max: -1 %>
                  <%= form.submit "-", :class => 'btn btn-warning text-dark font-weight-bold' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <hr >
      <div class="text-center">
        <%= link_to 'put in Order', edit_order_path(@cart.id), class: 'btn btn-success' %> |
        <%= link_to 'Remove', remove_cart_path(@cart.id), method: :delete, class: 'btn btn-danger' , data: { confirm: 'Are you sure?' } %></p>
    </div>
  <% else %>
    <table class="table table table-striped shadow rounded text-center mb-4">
      <tr>
        <td colspan="6" class="text-center h4">No Products Found</td>
      </tr>
    </table>
  <% end %>
</div>
</div>
</div>
</div>