config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  ### Landing Page
  root 'welcome#index'
  get 'welcome/index'
  ########################################################################

  ### User Routes
  devise_for :users, controllers: { confirmations: 'confirmations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ########################################################################
  
  ### Prdoduct Routes
  get "/fetch_products" => 'products#filter_products', as: 'fetch_products'
  resources :products
  ########################################################################

  ### Cart Routes
  get 'carts', to: 'carts#index', as: 'carts'
  post 'add.to.cart/:id', to: 'carts#create', as: 'add_to_cart'
  put 'cart/:id', to: 'carts#update', as: 'cart'
  delete 'remove.product/:id', to: 'carts#remove', as: 'remove_product'
  delete 'remove.cart/:id', to: 'carts#destroy', as: 'remove_cart'
  ########################################################################

  ### Order Routes
  get 'orders', to: 'orders#index', as: 'orders'
  get 'order/:id/edit', to: 'orders#edit', as: 'edit_order'
  put 'order/:id', to: 'orders#update', as: 'order'
  ########################################################################

  ### Store_Orders Routes
  get 'store.orders', to: 'store_orders#index', as: 'store_orders'
  get 'store.history', to: 'store_orders#history', as: 'store_history'
  put 'store.response/:id', to: 'store_orders#update', as: 'store_response'
  ########################################################################
  
  ### Reviews Routes
  post "rate.product/:id" => 'reviews#rate', as: 'rate_product'
  post "comment.product/:id" => 'reviews#comment', as: 'comment_product'
  ########################################################################
  
  ### Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  ########################################################################

  #Product API Routes
  namespace :api do
    resources :products
  end

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    belongs_to :brand
    belongs_to :store
    has_one_attached :image
    has_many :rates
    has_many :reviews
    has_many :order_products
    has_many :orders, through: :order_products
    has_many :coupon

    validates :title, presence: true, length: { minimum: 5 }
    validates :price, :quantity, numericality: true
    validates :description, :price, :quantity, :category_id, :brand_id, presence: true
    
    def self.search(search)
        if search.nil? || search.empty? 
            @products = self.all  
        else
            products = self.where("lower(title) LIKE lower(?) or lower(description) LIKE(?)", "%#{search}%", "%#{search}%")

            if products.exists?
                products
            else
                @products = []
            end
        end
    end

    def check_order(prod, id)
        @orders = Order.where(user_id: id, state: "delivered")
        if !@orders.empty?
            @orders.each do |order|
                if !(order.order_products).where(product_id: prod.id).empty?
                    return true
                end
            end
        end
        return false
    end

end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
    before_action :authenticate_user!, :except => [:index , :show]

    respond_to :json

    def index
        respond_with Product.all
    end
    def show
        respond_with Product.find(params[:id])
      end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    # load_and_authorize_resource
    before_action :authenticate_user!, :except => [:show, :index, :filter_products]
    before_action :filter_parameters
    # self.page_cache_directory = :domain_cache_directory
    caches_page :show

    @@searched_item = nil

    def index
        @@searched_item = params[:search]
        @filtered = false
        @products = Product.search(params[:search]).page params[:page]
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        @product.store_id = current_user.store.id

        if @product.save
            redirect_to @product
        else
            render 'new'
        end
    end

    def show
        @product = Product.find(params[:id])
        @rate = Rate.new
        @reviews = Review.where(product_id: params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        
        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end
    end

    # def destroy
    #     if check_orders()
    #         @product = Product.find(params[:id])
    #         @product.destroy
    #         redirect_to products_path
    #     else
    #         redirect_to products_path, alert: "cannot delete product in order process"
    #     end
    # end

    def filter_parameters
        @categories = Category.all
        @brands = Brand.all
        @stores = Store.all
    end

    def filter_products
        
        if params[:categories].present? || params[:brands].present? || params[:stores].present? || params[:price_min].present? || params[:price_max].present?
            @products = Product.search(@@searched_item)

            if params[:categories].present?
                @products = (@products.nil?) ? Product.where(category_id: params[:categories]) : @products.where(category_id: params[:categories])
            end

            if params[:brands].present?
                puts "brands = #{@brands}"
                @products = (@products.nil?) ? Product.where(brand_id: params[:brands]) : @products.where(brand_id: params[:brands])
            end   

            if params[:stores].present?
                @products = (@products.nil?) ? Product.where(store_id: params[:stores]) : @products.where(store_id: params[:stores])
            end

            if params[:price_min].present?
                @products = (@products.nil?) ? Product.where("price >= ?", params[:price_min]) : @products.where("price >= ?", params[:price_min])
            end

            if params[:price_max].present?
                @products = (@products.nil?) ? Product.where("price <= ?", params[:price_max]) : @products.where("price <= ?", params[:price_max])
            end

            @filtered = true
            @products

        else
            @filtered = false
            @products = Product.search(@@searched_item).page params[:page]
        end
        respond_to do |format|
            format.js
        end
    end

    private
        def product_params
            params.require(:product).permit(:title, :rate, :description, :price, :quantity, :category_id, :brand_id, :image, :page)
        end

        def domain_cache_directory
            Rails.root.join("public", request.domain)
        end

        def check_orders
            (OrderProduct.where(state: "pending", product_id: params[:id]).or(OrderProduct.where(state: "confirmed", product_id: params[:id]))).empty?
        end
end

app/helpers/api/products_helper.rb
module Api::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with scope: :product, url: products_path, local: true do |form| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@product.errors.count, "error") %> prohibited
            this article from being saved:
        </h2>
        <ul>
            <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'form-control mb-2' %>
    <div>
    
    <div class="form-group">
        <%= form.label :description %><br>
        <%= form.text_area :description, class: 'form-control mb-2' %>
    </div>

    <div class="form-group">
        <%= form.label :price %><br>
        <%= form.number_field :price, step: :any, class: 'form-control mb-2' %>
    </div>

    <div class="form-group">
        <%= form.label :quantity %><br>
        <%= form.number_field :quantity, class: 'form-control mb-2' %>
    </div>

    <div class="form-group">
        <%= form.label :category %><br>
        <%= form.collection_select :category_id, Category.all, :id, :name, {}, {class: 'custom-select mb-2'} %>
    </div>

    <div class="form-group">
        <%= form.label :brand %><br>
        <%= form.collection_select :brand_id, Brand.all, :id, :name, {}, {class: 'custom-select mb-2'} %>
    </div>

    <div class="custom-file">
        <%= form.file_field :image, class: 'custom-file-input' %>
        <%= form.label "Choose image", class: 'custom-file-label' %><br>
    </div>
    <hr>

    <div class="text-center">
        <%= form.submit 'Save Product', class: 'btn btn-lg btn-dark mt-3' %>
    </div>
    </div>

<% end %>

app/views/products/_product.html.erb
<article class="product mb-3 mr-3">
  <header>
    <%= link_to product do %>
      <%= (product.image.attached?) ? image_tag(product.image, size: "200x150", class: 'card-img-top mt-2 border') : image_tag("noprod.svg", size: "200x150") %>
    <% end %>
    <h4><%= product.title %></h4>
  </header>
  <footer class="actions">
    <% if product.quantity > 0 %>
      <%= link_to add_to_cart_path(product.id), class: 'btn btn-warning text-dark', method: :post do %>
        <%= fa_icon "shopping-cart", text: 'Add' %>
      <% end %>
    <% else %>
      <span class="text-danger">Out of stock</span>
    <% end %>
    <%= link_to product, class: 'btn btn-secondary pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>
  <aside class="price font-weight-bold">
    $<%=  product.price %>
  </aside>
  <% if product.quantity == 0 %>
    <%#= out_of_stock %>
  <% end %>
</article>

app/views/products/edit.html.erb
<div class="container">
  <div class="row flex-column align-items-center">
    <div class="m-2 p-4 border shadow col-md-6">
      <h2 class="text-center mb-5 bg-dark text-white rounded">Edit Product</h2>
      <%= render 'form'%>
    </div>
  </div>
  <%= link_to "Back to Products", products_path, class: 'btn btn-dark my-4 text-center' %>
</div>

app/views/products/filter_products.js.erb
<% if @products.present? %>
    $(".products").html("<%= escape_javascript( render @products ) %>");
<% else %>
    $(".products").html("<p style='text-align: center'>No Products Found</p>")
<% end %>

<% if @filtered %>
    $('.apple_pagination').hide()
<%else%>
    $('.apple_pagination').show()
<%end%>

app/views/products/index.html.erb
<div class="products-page container-fluid ">
  <div class="row m-1 justify-content-center">
    <%= render 'layouts/sidebar'%>
    <div class="main-content col-md-8 ml-3 p-3">
      <div class="d-flex flex-wrap border p-2 justify-content-center">
        <span class="px-2 py-1 align-self-center mr-3 d-md-none btn btn-outline-primary" onclick="showSidebar()">
          <i class="fas fa-filter"></i>
        </span>
        <% if current_user && current_user.seller_role? %>
          <div class="mr-3 align-self-center">
            <%= link_to "Add Product", new_product_path, class: 'd-inline btn-lg btn btn-outline-primary' %>
          </div>
        <% end %>
        <%# Search %>
        <%= form_tag products_path, :method => "get", class: 'search-form flex-nowrap form-inline justify-content-around' do %>
          <%= text_field_tag :search, params[:search], class: 'form-control mx-1', placeholder: 'Search' %>
          <%= submit_tag "Search", class: 'btn btn-dark', onclick: 'checkDimensions()' %>
        <% end %>
      </div>
      <div class="container mt-1 shadow p-2">
        <div class="products mb-5">
          <% if @products.present? %>
            <%= render @products %>
          <% else %>
            <p style="text-align: center">No Products Found</p>
          <% end %>
        </div>
      </div>
      <% if @products.present? %>
        <div class="apple_pagination border shadow rounded mt-5 p-1">
            <%= paginate @products %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row flex-column align-items-center">
    <div class="m-2 p-4 border shadow col-md-6">
      <h2 class="text-center mb-5 bg-dark text-white rounded">Add Product</h2>
      <%= render 'form'%>
    </div>
  </div>
  <%= link_to "Back to Products", products_path, class: 'btn btn-dark my-4 text-center' %>
</div>

app/views/products/show.html.erb
<%= stylesheet_link_tag 'product_details', media: 'all', 'data-turbolinks-track': 'reload' %>
<%# PRODUCT %>
<div class="row justify-content-center text-center border shadow m-4 p-4">
  <h1 class="col-md-11 bg-dark rounded p-2 shadow text-white">Product details</h1>
  <div class="col-md-5 ml-2 m-2 p-2">
      <%= (@product.image.attached?) ? image_tag(@product.image, size: "400*420", class: 'img-fluid') : image_tag("noprod.svg", size: "400*420", class: 'img-fluid') %>
    <div class="p-2 text-center">
      <%# ADD TO CART %>
      <% if @product.quantity > 0 %>
        <% if current_user %>
          <%= form_with(url: add_to_cart_path(@product.id), method: "post") do |form| %>
            <div class="col-md-8 text-center d-inline-flex">
              <%= form.number_field :quantity ,value: 1, min: 1, max: @product.quantity, :class => 'form-control d-inline-flex mr-3' %>
              <%= form.submit "Add to Cart", :class => 'btn btn btn-warning text-dark shadow' %>
            </div>
          <% end %>
        <% else %>
          <%= link_to "Add To Cart", add_to_cart_path(@product.id), class: 'btn btn-warning text-dark', method: :post %>
        <% end %>
      <% else %>
        <h4 class="border p-2 rounded text-danger">Out of stock</h4>
      <% end %>
      <%# END ADD TO CART %>
    </div>
  </div>
  <div class="col-md-5 bg ml-2 m-2">
    <br>
    <h1 class="mt-5"><%= @product.title %></h1>
    <hr>
    <p><b>Rate:</b> <%= @rate.product_rate(@product) %> | <b>Reviewers:</b> <%= @rate.reviewers(@product) %></p>
    <p><b>Price:</b> <%= @product.price %> | <b>AvailableQuantity:</b> <%= @product.quantity %></p>
    <p><b>Store:</b> <%= @product.store.name %></p>
    <p><b>Category:</b> <%= @product.category.name %> | <b>Brand:</b> <%= @product.brand.name %></p>
    <hr>
    <h5><b>Product Description</b></h5>
    <p class="border rounded mt-3 p-1 mb-3"><%= @product.description %></p>
    <div class="text-center">
      <% if can? :edit, @product %>
        <%= link_to "Edit", edit_product_path(@product.id), class: 'btn btn-primary shadow' %>
      <% end %>
    </div>
  </div>
</div>
<%# END PRODUCT %>
<% if current_user && current_user.id != @product.store.user_id && @product.check_order(@product, current_user.id) %>
  <%# REVIEWS %>
  <div class="row justify-content-center text-center border shadow m-4 p-4">
    <h3 class="col-md-11 bg-dark rounded p-2 shadow mb-3 text-white">Your Review</h3>
    <%# USER REVIEWS %>
    <div class="col-md-5 align-self-center">
      <div class="rounded p-2 m-1 text-center border rounded">
        <%# RATE %>
        <%= form_with(url: rate_product_path(@product.id), name: 'form', method: "post") do |f| %>
          <div class="rate text-center">
            <input type="radio" id="star5" name="rate" value="5" onclick="form.submit()"/>
            <label for="star5" title="excellent">5 stars</label>
            <input type="radio" id="star4" name="rate" value="4" onclick="form.submit()"/>
            <label for="star4" title="very good">4 stars</label>
            <input type="radio" id="star3" name="rate" value="3" onclick="form.submit()"/>
            <label for="star3" title="good">3 stars</label>
            <input type="radio" id="star2" name="rate" value="2" onclick="form.submit()"/>
            <label for="star2" title="poor">2 stars</label>
            <input type="radio" id="star1" name="rate" value="1" onclick="form.submit()"/>
            <label for="star1" title="bad">1 star</label>
          </div>
        <% end %>
        <p class="mt-2"><b>Your Rate: </b><% if !@rate.check_rate(@product, current_user.id) %><%= @rate.get_rate(@product, current_user.id) %><% else %>N/A<% end %></p>
        <%# END RATE %>
      </div>
    </div>
    <div class="col-md-5 align-self-center">
      <div class="rounded p-2 m-1 text-center">
        <%# COMMENT %>
        <% if (Review.new).check_reviews(@product, current_user) %>
          <%= form_with(url: comment_product_path(@product.id), method: "post") do |f| %>
            <%= f.text_area :comment, :class => 'form-control' %>
            <hr>
            <%= f.submit "review", :class => 'btn btn-outline-info shadow' %>
          <% end %>
        <% else %>
          <blockquote class="speech-bubble shadow"><%= @reviews.first.user_review(@product, current_user).comment %></p>
          <cite class="p-1 text-success"><b><%= current_user.name %></b></cite>
        </blockquote>
      <% end%>
      <%# END COMMENT %>
    </div>
  </div>
</div>
<%# END USER REVIEWS %>
<% end %>
<%# REVIEWS %>
<div class="row justify-content-center text-center border shadow m-4 p-4">
  <h3 class="col-md-11 bg-dark rounded p-2 shadow text-white">Reviews</h3>
  <div class="col-md-10 ml-2 m-1 p-2">
    <div class="p-3 m-2 text-center">
      <% if !@reviews.empty? %>
        <% @reviews.each do |review| %>
          <blockquote class="speech-bubble shadow"><%= review.comment %></p>
          <cite class="p-1"><b><%= link_to profile_path(review.user.id), :class => 'text-decoration-none text-dark' do %><%= review.user.name %><% end %></b></cite>
        </blockquote>
        <hr>
      <% end %>
    <% else %>
      <div class="mb-2 border">No Reviews</div>
    <% end %>
  </div>
</div>
</div>