config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  ### Landing Page
  root 'welcome#index'
  get 'welcome/index'
  ########################################################################

  ### User Routes
  devise_for :users, controllers: { confirmations: 'confirmations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ########################################################################
  
  ### Prdoduct Routes
  get "/fetch_products" => 'products#filter_products', as: 'fetch_products'
  resources :products
  ########################################################################

  ### Cart Routes
  get 'carts', to: 'carts#index', as: 'carts'
  post 'add.to.cart/:id', to: 'carts#create', as: 'add_to_cart'
  put 'cart/:id', to: 'carts#update', as: 'cart'
  delete 'remove.product/:id', to: 'carts#remove', as: 'remove_product'
  delete 'remove.cart/:id', to: 'carts#destroy', as: 'remove_cart'
  ########################################################################

  ### Order Routes
  get 'orders', to: 'orders#index', as: 'orders'
  get 'order/:id/edit', to: 'orders#edit', as: 'edit_order'
  put 'order/:id', to: 'orders#update', as: 'order'
  ########################################################################

  ### Store_Orders Routes
  get 'store.orders', to: 'store_orders#index', as: 'store_orders'
  get 'store.history', to: 'store_orders#history', as: 'store_history'
  put 'store.response/:id', to: 'store_orders#update', as: 'store_response'
  ########################################################################
  
  ### Reviews Routes
  post "rate.product/:id" => 'reviews#rate', as: 'rate_product'
  post "comment.product/:id" => 'reviews#comment', as: 'comment_product'
  ########################################################################
  
  ### Profile Routes
  get 'profile/:id', to: 'profiles#show', as: 'profile'
  ########################################################################

  #Product API Routes
  namespace :api do
    resources :products
  end

end

app/views/layouts/_foot.html.erb
<%# <h1>Footer</h1> %>
<div class="bg-dark text-center text-white p-1">
    <h2>Founders</h2>
    <div class="mt-3 mb-2 row justify-content-center founders">
        <a href="https://github.com/Ahmed-Abd-elhamid" class="btn btn-sm mr-3 btn-outline-info text-white">Abdelhamid</a>
        <a href="https://github.com/MuAladdinIbrahim" class="btn btn-sm mr-3 btn-outline-info text-white">Aladdin</a>
        <a href="https://github.com/Nouran96" class="btn btn-sm mr-3 btn-outline-info text-white">Nouran</a>
        <a href="https://github.com/zeyadsaleh" class="btn btn-sm btn-outline-info text-white">Zeyad</a>
    </div>
    <p>Website_GitHub &copy; <a href="https://github.com/Nouran96/ecommerce_rails"> E-commerce</a><p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="container p-2 text-center shadow rounded alert alert-<%= key %>">
    <h5 class="d-inline"><%= value %></h5>
    <a href="#" data-dismiss="alert" class="close text-right text-dark">×</a>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%if current_user %>
<% presenter = ImagePresenter.new(current_user) %>
<%else%>
<% presenter = ImagePresenter.new(nil) %>
<%end%>
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md bg-dark p-1 mb-3">
    <div class="container-fluid">
        <button class="navbar-toggler ml-2" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
                <li class='nav-item p-1 rounded'>
                    <%= link_to  welcome_index_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                        <%= fa_icon "home", class: 'text-white' %>
                        <span>Home</span>
                    <%end%>
                </li>  
                <li class='nav-item p-1 rounded'>
                    <%= link_to products_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                        <i class="fas fa-boxes"></i>
                        <span>Products</span>
                    <%end%>
                </li>  
            <% if current_user %>
                <li class='nav-item p-1 rounded'>
                    <%= link_to carts_path, class: 'nav-link text-white btn-outline-warning rounded btn-md' do %>
                        <i class="fab fa-opencart"></i>
                        <span>Cart</span>
                    <%end%>
                </li>
                <li class='nav-item p-1 rounded'>
                    <%= link_to orders_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                        <i class="fas fa-shipping-fast"></i>
                        <span>Orders</span>
                    <%end%>
                </li>
                <% if current_user.seller_role? %>
                    <li class='nav-item p-1 rounded'>
                        <%= link_to store_orders_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                            <i class="fas fa-store-alt"></i>
                            <span>Store</span>
                        <%end%>
                    </li> 
                    <li class='nav-item p-1 rounded'>
                        <%= link_to store_history_path, class: 'nav-link text-white btn-outline-secondary rounded btn-md' do %>
                            <i class="fas fa-history"></i>
                            <span>History</span>
                        <%end%>
                    </li> 
                <% end %>
            <% end %>
            </ul>
            <ul class="nav navbar-nav ml-auto">
            <% if current_user %>
                <li class='nav-item p-1 rounded d-none d-md-block'>
                    <%= link_to profile_path(current_user.id), title: current_user.name do %>
                        <%image_tag presenter.image, size: "40x40" ,class: "rounded-circle ml-2 mt-1" %>
                    <% end %>
                </li>                 
                <% if current_user.superadmin_role? %>
                        <li class='nav-item p-1 rounded'>
                            <%= link_to "/admin", class: 'nav-link text-white btn-outline-success rounded btn-md' do %>
                                <i class="fas fa-user-cog"></i>
                                <span>Dashboard</span>
                            <%end%>
                        </li> 
                <% end %>
                        <li class='nav-item p-1 rounded'>
                            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white btn-outline-danger rounded btn-md' do %>
                                <i class="fas fa-sign-out-alt"></i>
                                <span>Sign Out</span>
                            <%end%>
                        </li>
            <%else%>
                <li class='nav-item p-1 rounded'>
                    <%= link_to new_user_registration_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                        <i class="fas fa-user-plus"></i>
                        <span>Sign Up</span>
                    <%end%>
                </li>
                <li class='nav-item p-1 rounded'>
                    <%= link_to new_user_session_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                        <i class="fas fa-sign-in-alt"></i>
                        <span>Sign In</span>
                    <%end%>
                </li>
            <% end %>     
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="d-md-flex flex-column col-md-3 py-2 d-none shadow" id="sidebar-wrapper">

    <%# Filter %>
    <div class="filter">
        <div class="d-md-none my-3" id="close-filter" onclick="closeSidebar()">
            <span class="btn btn-dark rounded">X</span>
        </div>
        <%= form_tag fetch_products_path ,method: 'get', :remote => true, id: 'category-form' do %>
            <div class="category-filter mb-4 mt-3">
                <h4 class="bg-info p-1 rounded">Categories</h4>
                <% @categories.each do |category| %>
                    <div>
                        <%= check_box_tag "categories[]", category.id %>
                        <%= category.name %>
                    </div>
                <%end%>
            </div>
            <hr>
            <div class="brand-filter mb-4">
                <h4 class="bg-info p-1 rounded">Brands</h4>
                <% @brands.each do |brand| %>
                    <div>
                        <%= check_box_tag "brands[]", brand.id %>
                        <%= brand.name %>
                    </div>
                <%end%>
            </div>
            <hr>
            <div class="store-filter mb-4">
                <h4 class="bg-info p-1 rounded">Stores</h4>
                <% @stores.each do |store| %>
                    <div>
                        <%= check_box_tag "stores[]", store.id %>
                        <%= store.name %>
                    </div>
                <%end%>
            </div>
            <hr>
            <div class="price-filter mb-4">
                <h4 class="bg-info p-1 rounded">Prices</h4>
                <div class="form-group">
                    <%= label_tag 'Min: '%>
                    <%= number_field_tag 'price_min', nil, class: 'form-control d-inline-block' %>
                </div>

                <%= label_tag 'Max: '%>
                <%= number_field_tag 'price_max', nil, class: 'form-control' %>
            </div>
            <%= submit_tag "Filter", class: 'btn btn-success shadow w-100', onclick: 'checkDimensions()' %>
        <% end %>

    </div>

</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SouCom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'cart.svg' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'products', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js' %>
  </head>

  <body class="d-flex flex-column justify-content-between">
    <header class="">
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
    </header>
    <div class="">
      <%= yield %>
    </div>
    <footer class="bg-dark mt-5">
      <%= render 'layouts/foot' %>
    </footer>
  </body>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script>
    var x = window.matchMedia("(max-width: 767px)")

    var path = window.location.pathname

    if(path.includes("welcome") || path == '/') {
      $('body').addClass("welcome");
    }
    
    function showSidebar(){
      $('#sidebar-wrapper').removeClass('d-none')
    }

    function closeSidebar(){
      $('#sidebar-wrapper').addClass('d-none')
    }

    function checkDimensions(){      
      if(x.matches) {
        closeSidebar()
      }
    }
  </script>
</html>